# -*- coding: utf-8 -*-
"""conditional_statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZE5aMzsglFF2CThqtlzq2Af2ud7BjF6
"""

#to take age input from the user and see if he/she is elig for voting or not

age = int(input("enter your age: "))
if age<18:
    print("you are not elig")
else:
  print("you are elig")

#take len & breadth of the react & check if the reactangle is square or not



length = int(input("enter the len of the reactangle: "))
breadth = int(input("enter the bre of the reactangle: "))
if length == breadth:
  print("it is a square")
else:
  print("it is a reactangle")

'''In a fare, the entry fee is 0 rupees for children less than 4 years of age. Entry fee is 100 rupees if the age is between 4-18 years and if the
age is more than 18 years, the entry fee is 175 rupees.
Take age as input from the user and display the ticket price'''

age = int(input("enter your age:  "))
if age<4:
  print("your entry is free")
elif age<=18:
  print("your entry fees is Rs.100")
else:
  print("your entry fees is Rs. 175")

#Take a number as input from the user and check if it is perfectly divisible by 2, 3 and 7 or not
num = int(input("enter the num: "))
if num%2==0:
  print("it is divisible by 2")
else:
  print("the num is not divisible by 2")
if num%3==0:
  print("it is divisible by 3")
else:
  print("the num is not divisible by 3")
if num%7==0:
  print("it is divisible by 7")
else:
  print("the num is not divisible by 7 ")

#take a num from user and check if it is even or odd

num = int(input("enter the num: "))
if num%2==0:
  print("it is a even num")
else:
  print("the num is a odd num")

'''The owner of a company decides to give bonus of 5% to employees who have been working in the company for 5 years or more.

Take current salary and years of experience with the current company as input and print the incremented salary (if any)'''

sal = int(input("enter your salary: "))
year = int(input("enter your total year of working: "))
company = input("enter your company name: ")

if year>=5:
  print("your increment salary is ", sal+0.05*sal)
else:
  print("you are not elig")

no_of_items = int(input("enter the num of item purchased: "))
total_amt = 200*no_of_items

if no_of_items>=10:
  discounted_price=total_amt-0.20*total_amt
  print("discounted price is ", discounted_price)
else:
  print("no discount applied")

#take input from the user and chck if it is +ve, -ve or 0

num= int(input("enter the num: "))

if num>=0:
  if num>0:
    print("the num is +ve")
  else:
    print("the num is 0")
  
else:
  print("the num is -ve")

for i in range (1,20,2):
  print(i)

# H/W- Take a number as input from the user and check if it is positive or negative. In either case check if the number is even number or an odd 
# number

num= int(input("enter your num: "))

if num>=0:
  if num%2==0:
    print("it is a +ve even number")
  else:
    print("it is a +ve odd number")
elif num%2==0:
  print("it is a -ve even number")
else:
  print("it is a -ve odd number")

c=0
while c<20:
  print(c)
  c=c+2

"""take a list of your choice and display the even ones only and count it"""

l1=[2,3,5,6,7,10,12]

count=0
count1=0
for i in l1:
  if i%2==0:
    count=count+1 #if there is an even num the count will increase itself
  else:
    count1=count1+1 #if there is an even num the count will increase itself
print('the total num of even num is', count)
print('the total num of odd num is', count1)

"""take a number as input from the user and display the multiplication table till 10 for that number"""

num = int(input("enter your num: "))

for i in range(1,11):
  print(num, 'x', i, '=', num*i)

"""Calculate the sum and average of all numbers from 1 to a given number by the user"""

num = int(input("enter your num: "))

sum=0
for i in range(1,num):
  sum=sum+i
print("the sun of the num is", sum)
avg=sum/num
print("the avg of the num is",avg)

l1=[1,2,3,4,5,6,7,8,9,10,]

for i in l1:
  if i==3 or i==7:
    continue
  print(i)

"""take a list of number and append the squares in a separate list"""

l1=[2,3,5,6,7,10,12]

list=[]
for i in l1:
  if i%2==0:
    sq = i**2
    list.append(sq)
print(list)

#TAKE A LIST OF NUM AND DISPLYA ALL THE EVEN NUMBER FROM THE LIST
l1=[2,3,5,6,7,10,12]

list=[]
for i in l1:
  if i%2==0:
    list.append(i)
print(list)

