# -*- coding: utf-8 -*-
"""python_basics_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gq63WYUdIpfiykULYSmmkiF_eTDlnQLJ

Concatination
"""

#command - used to increase readeblity of code - it is not going to get executed

#strings
a='My'
b='India'

print(a+b)

print(a+' '+b)

p='Prime'
l=['Monday','Tuesday']

print(p+l) #will give an error because contatination can't happen between str & list

q=list(p) #the string datatype gets converted to list datatype

print(q+l)

#lists
l1=[3,4,56,90,23,78,45]
l2=['India','UK','US','China']
l3=['Mango','Apple','Pineapple']

print(l1+l2+l3)

name=input("enter your name ")
a="Hi"
b="how are you?"
c="Please have a seat"

print(a+' '+name+' '+b+' '+c)

"""Indexing"""

#strings
a='Indian Ocean'

a[3]

a[9]

a[-4]

a[0]

#list
l1=['India','China','Bhutan','Pakistan',45,30,20.25,-400]

l1[3]

l1[-3]

l1[-5]

l1[6]

l1[10] #this will give an error because there is no index till 10

"""Slicing"""

#strings
a='United Nations'

a[0:6]

a[7:]

a[-7:]

a[:]

a[:4]

a[:-3]

b=a[7:] #Nations
c=a[0:6] #United
print(b+" "+c)

a[-14:-1]

a[-11:-5]

a[:-10]

a[-6:-1]

print(a)

a[0:6:2]

a[4:9:3]

a[7::3]

b='Indian Ocean'

b[1:9:4]

b[1:9:3]

"""NESTED LIST"""

l1=['India','US','UK','Germany',['Delhi','Mumbai','Varanasi']]

l1[4][0]

l1[4][0:2]

#delhi and varanasi
l1[4][0::2]

L2=['Mango','Banana','Grapes',['Pune','Hyderabad','Bangalore'],['DataScience', 'MachineLearning']]

"""[MachineLearning, Hyderabad, Bangalore,Banana,Grapes]

[MachineLearning,Bangalore,Hyderabad,Grapes,Banana]
"""

a=L2[4][:]

print(a)

b=L2[3][1:]

print(b)

type(b)

c=L2[1:3]

print(c)

type(c)

print(a+b+c)

print("["+L2[4][1]+" ,"+L2[3][2]+" ,"+L2[3][1]+" ,"+L2[2]+" ,"+L2[1]+"]")

L2[4][2::]+L2[3][1::]+L2[1:3]

L2[4][1]+","+L2[3][2]+","+L2[3][1]+","+L2[2]+","+L2[1]

a=L2[4][1]
d=list(a)
b=L2[3][1:]
e=list(b)
c=L2[1:3]
f=list(c)
print(d+e+f)

type(a)

type(d)

a=L2[4][1]
b=L2[3][1]
c=L2[3][2]
d=L2[1]
e=L2[2]

print(a,c,b,e,d)

"""Built in Functions - LISTS"""

l1=['AI','NLP','Computer Vision','DataScience']

l1.append("Deeplearning") #will add the element at the end of the list

print(l1)

l1.insert(3,'NLP') #will add the element at the desired index position

print(l1)

l2=[34,35,89,90]

l2.append(900)

print(l2)

l2.insert(2,300)

print(l2)

print(l1)

l1.remove('NLP') #will delete the first occurance of the given element

print(l1)

l1.pop(3) #will delete the element from the desired index position

print(l1)

l1.extend(['statistics','algerbra','R programming'])

print(l1)

len(l1) #will count the total number of elements in the list

len(l2)

l3=[67,78,34,67,22,90,56,78,67,12]

len(l3)

l3.count(67) #will count the frequency of the given element

l3.count(90)

max(l3)

min(l3)

sum(l3)

l3.sort()

print(l3)

