# -*- coding: utf-8 -*-
"""python_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baMfXG3g6Yp-5dA-oVTLF8OJnU1nYNIz

built in functions
"""

#how to execute the code cell?
#ctrl+enter
#shift+enter
#use the play button

name="Rohit"

print(name)

type(name)

a=35.50

print(a)

type(a)

b=-40

print(b)

type(b)

l1=[35,40,-20,'India','Israel','US']

print(l1)

type(l1)

a=45
b=20
print(a>b)

type(a>b)

print(a<b)

type(a<b)

name=input("enter your name ")

print(name)

#typecasting
otp=int(input("enter otp "))

type(otp)

temp=float(input("enter temp of your city "))

print(temp)

type(temp)

